# -*- coding: utf-8 -*-
"""ADA_Project_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXVunjhHLDwuUaIqy9VTUOvn8UfclD9o

# The Impact of Cultural Participation on National Innovation
**Abstract:** This study explores the link between cultural engagement and innovation performance across 32 European nations. By integrating Eurostat cultural data with the European Innovation Scoreboard (2022-2025), it evaluates if cultural participation meaningfully contributes to economic innovation.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

"""1. Data Import"""

# Eurostat cultural participation data (2022)
culture_path = "/content/ilc_scp03$dv_550_page_spreadsheet.xlsx"
# European Innovation Scoreboard data
eis_path = "/content/EIS_web_download.xlsx"

culture_raw = pd.read_excel(culture_path)
eis_raw = pd.read_excel(eis_path)

# Inspect the structure
culture_raw.head(), eis_raw.head()

"""2. Cleaning cultural participation data"""

culture = culture_raw.copy()

# Standardise column names
culture.columns = culture.columns.str.lower()

# Drop useless rows
culture = culture.drop(index=[0])
culture.head()

# Rename key columns (adjust if naming differs slightly)
culture = culture.rename(columns={
    "acl00 (labels)": "country",
    "cultural activities (cinema, live performances or cultural sites)": "participation_rate"
})

indices_to_drop = culture[culture["participation_rate"] == ":"].index

# Drop the identified rows
culture.drop(indices_to_drop, inplace=True)

culture["participation_rate"] = pd.to_numeric(
    culture["participation_rate"],
    errors="coerce"
)

print(culture)

"""3. Cleaning European Innovation Scoreboard data"""

eis = eis_raw.copy()
# Standardise column names
eis.columns = eis.columns.str.lower()

# The EIS contains many indicators, retain only the headline index
eis_sii = eis[
    eis["indicator"].str.contains("Summary Innovation Index", case=False, na=False)
]
# Pivot to obtain country–year values
eis_sii_pivot = (
    eis_sii
    .pivot_table(
        index=["country", "year"],
        values="value",
        aggfunc="mean"
    )
    .reset_index()
)
# Rename and clean
eis_sii_pivot = eis_sii_pivot.rename(
    columns={"value": "innovation_score"}
)
eis_sii_pivot["innovation_score"] = pd.to_numeric(
    eis_sii_pivot["innovation_score"], errors="coerce"
)

# Keep recent years (2022–2025)
eis_sii_pivot = eis_sii_pivot[
    eis_sii_pivot["year"].between(2022, 2025)
]
eis_sii_pivot.head()

"""4. Merging datasets"""

# Merge cultural participation with innovation scores
data = eis_sii_pivot.merge(
    culture,
    on="country",
    how="inner"
)

# Drop missing observations
data = data.dropna(subset=["innovation_score", "participation_rate"])
print(data)

""" 5. Descriptive statistics"""

desc_stats = data[[
    "participation_rate",
    "innovation_score"
]].describe()

print(desc_stats)

"""6. Exploratory visualisation"""

# Visualisation to help identify patterns
plt.figure(figsize=(7,5))
sns.regplot(
    data=data,
    x="participation_rate",
    y="innovation_score",
    scatter_kws={"alpha": 0.6}
)
plt.xlabel("Average cultural participation rate (2022)")
plt.ylabel("Innovation performance score")
plt.title("Cultural participation and innovation performance in the EU")
plt.tight_layout()
plt.show()

"""7. Correlation analysis"""

# Compute Pearson correlation between cultural participation and innovation performance
corr = data[["participation_rate", "innovation_score"]].corr()
print(corr)

"""8. Predective modeling"""

X = data[["participation_rate"]]
y = data["innovation_score"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42
)

# Linear Regression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

y_pred_lr = linreg.predict(X_test)

print("Linear regression R²:", r2_score(y_test, y_pred_lr))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_lr)))

# Random Forest Regressor
rf = RandomForestRegressor(
    n_estimators=500,
    random_state=42
)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

r2 = r2_score(y_test, y_pred_rf)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))

print("Random forest R²:", r2_score(y_test, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_rf)))